# Generated by Django 2.0.6 on 2018-06-27 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180626_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
